### ISSUE TITLE
Alphabetize filters

### ISSUE THREAD

**Issue by akercheval** [jumbocodefall2017/BINJ#15]
See title - everything in the filter section should be alphabetized, and authors should be alphabetized by last name.

**Comment by akercheval** [comment]
Story types are sorted successfully, and I can get authors to sort properly on my local instance of the app, but not on the heroku instance. Very perplexing.

**Comment by grimtrigg** [comment]
Awesome, glad to hear that it works with the story types! I wish I had some suggestions for the authors problem, but I don’t. That is strange. Let me know if you make any progress with it.

**Comment by akercheval** [comment]
This is extremely close to being done, except for one issue: on the heroku-served site, all the authors are organized alphabetically, but (presumably) the first author in the original list of authors, Karen Morales, shows up at the front of the list as well as in the correct position. No idea why this happens.
![image](https://user-images.githubusercontent.com/15968944/37261169-be64e090-2570-11e8-8fe6-88751ea8b8a1.png)
