### ISSUE TITLE
New Story Image AutoFill

### ISSUE THREAD

**Issue by ajohns619** [jumbocodefall2017/BINJ#17]
When creating a new article, after entering the page url, the admin page should automatically fill out the image url field as well, with the image displayed on the page. The image url can be guessed using the imgurl route (example: https://binj-map.herokuapp.com/imgurl?url=http://baystatebanner.com/news/2017/dec/20/activists-call-us-govt-cancel-puerto-rico-debt/). Since that is just a guess, the user should still be able to change the url if they want a different picture to appear.

**Comment by ajohns619** [comment]
I created a version with all the above functionality. Three things to add:
- better error handling (for example and error message) when the story url is invalid
- better styling of the image on the admin page (maybe?)
- imgurl selects the wrong image for any digboston articles, so tweek the imgurl route specifically for that domain, since binj seems to link to that site a lot

**Comment by ajohns619** [comment]
Fixed digbotston issue by adding site-specific scrape.

**Comment by akercheval** [comment]
Has this been pushed to master and tested? If so, we can close the issue

**Comment by ajohns619** [comment]
Yes, this is finished.
