### ISSUE TITLE
We need an API key for Google

### ISSUE THREAD

**Issue by wwmairs** [jumbocodefall2017/BINJ#2]
How do you want me and Daniel to register an API key? Do you want some kinda BINJ-specific thing that can be transferred after we're done building all this nonsense?
tytytyty

**Comment by akercheval** [comment]
Resolved during weekly meeting - make a BINJ gmail account and register the key to it, and then when we ship the product we can let the BINJ people know how to transfer ownership if they want

**Comment by dnavon2557** [comment]
did we ever get a key?
